In [2]:
from pathlib import Path
import pandas as pd

SESSION_ID = "VS15_2022-03-01_16-02-15"

repo = Path.cwd().resolve()
if not (repo / "data").exists():
    repo = Path(r"C:/Users/tadse/OneDrive/Documenti/GitHub/CA1-cellclass").resolve()

mouse = SESSION_ID.split("_", 1)[0]
ssi_path = repo / "data" / "processed" / mouse / "ssi" / SESSION_ID / "ssi_classification.csv"

if not ssi_path.exists():
    raise FileNotFoundError(f"Could not find SSI classification CSV:\n{ssi_path}")

ssi_df = pd.read_csv(ssi_path)

print(f"Loaded {len(ssi_df)} rows from:")
print(ssi_path)
display(ssi_df.head())

Loaded 42 rows from:
C:\Users\tadse\OneDrive\Documenti\GitHub\CA1-cellclass\data\processed\VS15\ssi\VS15_2022-03-01_16-02-15\ssi_classification.csv

,session_id,cell_id,cell_type,classification_certainty,p_pred_type,Sure (P(pred_type) > 0.6),age_group,condition_1b,Condition,direction,ssi_obs,p_value,SM,sm_alpha
0,VS15_2022-03-01_16-02-15,14,pyramidal,sure,0.998856,True,P22-24,1,PO,W,0.098691,0.002997,True,0.05
1,VS15_2022-03-01_16-02-15,14,pyramidal,sure,0.998856,True,P22-24,2,PO,B,0.044323,0.025974,True,0.05
2,VS15_2022-03-01_16-02-15,14,pyramidal,sure,0.998856,True,P22-24,3,PO2,W,0.123713,0.000999,True,0.05
3,VS15_2022-03-01_16-02-15,14,pyramidal,sure,0.998856,True,P22-24,4,PO2,B,0.073203,0.000999,True,0.05
4,VS15_2022-03-01_16-02-15,14,pyramidal,sure,0.998856,True,P22-24,5,PO3,W,0.047103,0.034965,True,0.05

In [3]:
ssi_df[ssi_df["ssi_obs"].isna() | ssi_df["p_value"].isna()] \
    .groupby(["session_id", "Condition", "direction"]) \
    .size() \
    .reset_index(name="n_nan_rows")

                 session_id Condition direction  n_nan_rows
0  VS15_2022-03-01_16-02-15       PO2         W           1
1  VS15_2022-03-01_16-02-15       PO3         B           1
2  VS15_2022-03-01_16-02-15       PO3         W           1